In [5]:
# -*- coding: utf-8 -*-
"""
Created on Sat Mar 17 19:28:29 2018

@author: yangx
"""

import numpy as np
r=np.array([4,3.8,3.4,3,2.5])
c=np.array([0.5,0.6,0.7,0.9,1.2])
w=np.array([4,3.5,3,2.4,1])
V=np.mat(np.zeros((6,6)))
f=np.mat(np.zeros((5,5)))
f[:,-1]=1                       #1为更换，0为保留，i=4时必须更换
for n in np.arange(4,-1,-1):
    for i in np.arange(5):
        if i==4:
            V[n,4]=-1.5+w[0]+V[n+1,1]
            print(V[n,4])
            continue
        if r[i]-c[i]+V[n+1,i+1]<-1.5+w[i]+V[n+1,1]:
            f[n,i]=1
        V[n,i]=max(r[i]-c[i]+V[n+1,i+1],-1.5+w[i]+V[n+1,1])
        print(V[n,i])
OptVal=V[:5,:5]    #只取前五行五列（其余的为0）
OptStr=f
print('最优值函数矩阵（阶段*状态）为：')
print('\n')
print(OptVal)
print('******************************************************')
print('最优策略函数矩阵（阶段*状态）为：')
print('\n')
print(OptStr)

3.5
3.2
2.7
2.1
2.5
6.7
5.9
4.8
4.6
5.7
9.4
8.0
7.4
7.8
8.4
11.5
10.6
10.5
10.5
10.5
14.1
13.7
13.2
12.6
13.1
最优值函数矩阵（阶段*状态）为：


[[ 14.1  13.7  13.2  12.6  13.1]
 [ 11.5  10.6  10.5  10.5  10.5]
 [  9.4   8.    7.4   7.8   8.4]
 [  6.7   5.9   4.8   4.6   5.7]
 [  3.5   3.2   2.7   2.1   2.5]]
******************************************************
最优策略函数矩阵（阶段*状态）为：


[[ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  1.  0.  1.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  1.]]
