In [1]:
import numpy as np

In [2]:
r=np.array([4,3.8,3.4,3,2.5])
c=np.array([0.5,0.6,0.7,0.9,1.2])
w=np.array([4,3.5,3,2.4,1])
#P=np.mat([[0.8,0.1,.05,.05,0],[0,.7,.2,.1,0],[0,0,.6,.3,.2],[0,0,0,.5,.5],[0,0,0,0,1])，原5*5的P矩阵无法与6*6的V矩阵相乘
P=np.mat([[0.8,0.1,.05,.05,0,0],[0,.7,.2,.1,0,0],[0,0,.6,.3,.2,0],[0,0,0,.5,.5,0],[0,0,0,0,1,0]])  #加一列0向量，成为5*6矩阵，不影响结果
V=np.mat(np.zeros((6,6)))
f=np.mat(np.zeros((5,5)))
f[:,-1]=1
f                       #1为更换，0为保留，i=4时必须更换

matrix([[ 0.,  0.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  1.]])

In [3]:
for n in np.arange(4,-1,-1):
    for i in np.arange(5):
        if i==4:
            V[n,4]=-1.5+w[4]+np.dot(P,V.T)[0,n+1]
            #print(V[n,4])
            continue
        if r[i]-c[i]+np.dot(P,V.T)[i,n+1]<-1.5+w[i]+np.dot(P,V.T)[0,n+1]:
            f[n,i]=1
        V[n,i]=max(r[i]-c[i]+np.dot(P,V.T)[i,n+1],-1.5+w[i]+np.dot(P,V.T)[0,n+1])
        #print(V[n,i])
OptVal=V[:5,:5]    #只取前五行五列（其余的为0）
OptStr=f
print('最优值函数矩阵（阶段*状态）为：')
print('\t')
print(OptVal)
print('******************************************************')
print('最优策略函数矩阵（阶段*状态）为：')
print('\t')
print(OptStr)

最优值函数矩阵（阶段*状态）为：
	
[[ 16.34888  14.84888  14.46178  13.74888  12.34888]
 [ 13.2198   11.8106   11.2198   10.6198    9.2198 ]
 [ 10.063     8.931     8.063     7.463     6.063  ]
 [  6.86      6.19      4.86      4.26      2.86   ]
 [  3.5       3.2       2.7       2.1      -0.5    ]]
******************************************************
最优策略函数矩阵（阶段*状态）为：
	
[[ 0.  1.  0.  1.  1.]
 [ 0.  0.  1.  1.  1.]
 [ 0.  0.  1.  1.  1.]
 [ 0.  0.  1.  1.  1.]
 [ 0.  0.  0.  0.  1.]]
